# Workflow para construir y probar un proyecto Java con Maven en GitHub Actions
# Este archivo configura GitHub Actions para ejecutar la integración continua (CI) de un proyecto Java.
# Construye y ejecuta pruebas automáticas con Maven cada vez que hay un push o pull request a la rama 'main'.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Paso 1: Descargar el código del repositorio
    - uses: actions/checkout@v4

    # Paso 2: Configurar JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Paso 3: Construir y ejecutar pruebas con Maven
    - name: Build and Test with Maven
      run: mvn -B package --file pom.xml

    # Paso 4: Configurar GitHub Actions para ejecutar pruebas en cada push a main
    - name: Run Tests
      run: mvn test
